#!/usr/bin/env node

/**
 * Interactive Setup Script
 *
 * Usage: npm run setup
 *
 * Guides users through:
 *   1. Gmail App Password creation
 *   2. .env configuration
 *   3. Database initialization
 *   4. Connection verification
 *   5. Sending a test email
 */

import readline from 'readline';
import { writeFileSync, existsSync, readFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';
import { execSync } from 'child_process';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const PROJECT_ROOT = join(__dirname, '..');

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});

function ask(question) {
  return new Promise(resolve => rl.question(question, resolve));
}

function print(msg = '') {
  console.log(msg);
}

function header(text) {
  print();
  print('═'.repeat(55));
  print(`  ${text}`);
  print('═'.repeat(55));
  print();
}

function step(num, text) {
  print(`  [${num}] ${text}`);
}

async function main() {
  header('Job Auto-Apply — Setup');

  print('  This wizard will help you set up everything.');
  print('  You will need:');
  print('    - A Gmail account');
  print('    - A phone number (for 2-Step Verification)');
  print();

  const ready = await ask('  Ready to start? (y/n): ');
  if (ready.toLowerCase() !== 'y') {
    print('\n  No problem. Run "npm run setup" when you\'re ready.\n');
    rl.close();
    return;
  }

  // === Step 1: Gmail Info ===
  header('Step 1/5 — Gmail Account');

  const email = await ask('  Your Gmail address: ');
  const name = await ask('  Your full name: ');

  if (!email.includes('@')) {
    print('\n  ✗ Invalid email. Please restart setup.\n');
    rl.close();
    return;
  }

  // === Step 2: App Password ===
  header('Step 2/5 — Gmail App Password');

  print('  To send emails, you need a Gmail App Password.');
  print('  Follow these steps:\n');
  step(1, 'Enable 2-Step Verification (if not already):');
  print('      → https://myaccount.google.com/signinoptions/two-step-verification');
  print();
  step(2, 'Create an App Password:');
  print('      → https://myaccount.google.com/apppasswords');
  print('      → App name: "Job Apply"');
  print('      → Click "Create"');
  print('      → Copy the 16-character password');
  print();

  const appPassword = await ask('  Paste your App Password here: ');
  const cleanPassword = appPassword.replace(/\s/g, '');

  if (cleanPassword.length !== 16) {
    print(`\n  ⚠ Expected 16 characters, got ${cleanPassword.length}.`);
    const cont = await ask('  Continue anyway? (y/n): ');
    if (cont.toLowerCase() !== 'y') {
      rl.close();
      return;
    }
  }

  // === Step 3: Write .env ===
  header('Step 3/5 — Configuration');

  const dailyLimit = await ask('  Daily email limit (default 25): ') || '25';

  const envContent = [
    '# Generated by setup script',
    'EMAIL_PROVIDER=gmail-app-password',
    '',
    `FROM_EMAIL=${email}`,
    `FROM_NAME=${name}`,
    `GMAIL_APP_PASSWORD=${cleanPassword}`,
    '',
    `DAILY_LIMIT=${dailyLimit}`
  ].join('\n') + '\n';

  const envPath = join(PROJECT_ROOT, '.env');

  if (existsSync(envPath)) {
    const overwrite = await ask('  .env already exists. Overwrite? (y/n): ');
    if (overwrite.toLowerCase() !== 'y') {
      print('  Skipped .env write.');
    } else {
      writeFileSync(envPath, envContent);
      print('  ✓ .env updated');
    }
  } else {
    writeFileSync(envPath, envContent);
    print('  ✓ .env created');
  }

  // === Step 4: Initialize DB ===
  header('Step 4/5 — Database');

  print('  Initializing SQLite database...');
  try {
    execSync('node src/db/init.js', { cwd: PROJECT_ROOT, stdio: 'inherit' });
    print('  ✓ Database ready');
  } catch {
    print('  ✗ Database initialization failed. Run "npm run init-db" manually.');
  }

  // === Step 5: Verify Connection ===
  header('Step 5/5 — Verify Connection');

  print('  Testing SMTP connection...');
  try {
    execSync('node src/index.js verify', { cwd: PROJECT_ROOT, stdio: 'inherit' });
  } catch {
    print('  ✗ Connection failed. Check your App Password and try again.');
    print('    Run "node src/index.js verify" to retry.\n');
    rl.close();
    return;
  }

  print();
  print('  Testing IMAP connection...');
  try {
    execSync('node src/index.js profile', { cwd: PROJECT_ROOT, stdio: 'inherit' });
    print('  ✓ IMAP works — you can read emails');
  } catch {
    print('  ⚠ IMAP connection failed. Send will work, but inbox reading may not.');
    print('    Make sure IMAP is enabled in Gmail Settings → Forwarding and POP/IMAP');
  }

  // === Optional: Test Email ===
  print();
  const testEmail = await ask('  Send a test email? Enter recipient (or press Enter to skip): ');

  if (testEmail && testEmail.includes('@')) {
    print(`\n  Sending test email to ${testEmail}...`);
    try {
      // Add test contact
      execSync(
        `node src/index.js add-contact -e "${testEmail}" -n "Test" -f "Test" -c "Setup Test" --source "setup script"`,
        { cwd: PROJECT_ROOT, stdio: 'pipe' }
      );

      // Find the contact ID
      const listOutput = execSync('node src/index.js list', { cwd: PROJECT_ROOT, encoding: 'utf-8' });
      // Get the latest contact ID from the database
      const idOutput = execSync(
        `node -e "import Database from 'better-sqlite3'; const db = new Database('./data/job-apply.db'); const r = db.prepare(\\"SELECT MAX(id) as id FROM contacts\\").get(); console.log(r.id); db.close();"`,
        { cwd: PROJECT_ROOT, encoding: 'utf-8' }
      ).trim();

      // Schedule and immediately send
      execSync(
        `node src/index.js schedule -c ${idOutput} -t cold_general -d '{"specific_detail":"your product","achievement_1":"This is a test email from Job Auto-Apply setup","achievement_2":"If you received this, the setup is working!"}'`,
        { cwd: PROJECT_ROOT, stdio: 'pipe' }
      );

      // Update scheduled_at to now
      execSync(
        `node -e "import Database from 'better-sqlite3'; const db = new Database('./data/job-apply.db'); db.prepare(\\"UPDATE emails SET scheduled_at = datetime('now') WHERE status = 'scheduled'\\").run(); db.close();"`,
        { cwd: PROJECT_ROOT, stdio: 'pipe' }
      );

      execSync('node src/index.js send', { cwd: PROJECT_ROOT, stdio: 'inherit', timeout: 30000 });
      print('  ✓ Test email sent! Check the recipient inbox.');
    } catch (e) {
      print(`  ✗ Failed to send test email: ${e.message}`);
    }
  }

  // === Done ===
  header('Setup Complete!');

  print('  Your job application system is ready.\n');
  print('  Next steps:');
  print('    1. Add companies:');
  print('       node src/index.js add-company -n "Cool Startup" -i "AI" -p 5');
  print();
  print('    2. Add contacts:');
  print('       node src/index.js add-contact -e hi@startup.com -n "Jane" -c "Cool Startup"');
  print();
  print('    3. Schedule emails:');
  print('       node src/index.js schedule -c 1 -t cold_general');
  print();
  print('    4. Send:');
  print('       node src/index.js send --dry-run  # preview');
  print('       node src/index.js send            # for real');
  print();
  print('    5. Check replies:');
  print('       node src/index.js check-replies');
  print();
  print('  Full docs: README.md');
  print();

  rl.close();
}

main().catch(err => {
  console.error('Setup failed:', err.message);
  rl.close();
  process.exit(1);
});
